Node module name seems to have changed
Change seems to be now 'ahoi-nodejs-client'. You b.t.w. need to have portable-fetch installed, to.
Furthermore I found npm run build not working:
"error TS5014: Failed to parse file '/Users/karsten/tmp/RH/ahoi-nodejs-client/tsconfig.json': Unexpected token } in JSON at position 508."